/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FbAccountsRouteImport } from './routes/fb-accounts'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdAccountsRouteImport } from './routes/ad-accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperationsTaskIdRouteImport } from './routes/operations_.$taskId'
import { Route as FbAccountsIdRouteImport } from './routes/fb-accounts_.$id'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdminOperationsRouteImport } from './routes/admin_.operations'
import { Route as AdminIamRouteImport } from './routes/admin_.iam'
import { Route as AdminCompanyRouteImport } from './routes/admin_.company'
import { Route as AdminAuditRouteImport } from './routes/admin_.audit'
import { Route as AdAccountsIdRouteImport } from './routes/ad-accounts_.$id'
import { Route as OauthFbCallbackRouteImport } from './routes/oauth.fb.callback'
import { Route as AdminOperationsTaskIdRouteImport } from './routes/admin_.operations_.$taskId'
import { Route as AdAccountsIdCampaignsCidRouteImport } from './routes/ad-accounts_.$id_.campaigns_.$cid'
import { Route as AdAccountsIdCampaignsCidAdsetsAsidRouteImport } from './routes/ad-accounts_.$id_.campaigns_.$cid_.adsets_.$asid'

const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FbAccountsRoute = FbAccountsRouteImport.update({
  id: '/fb-accounts',
  path: '/fb-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdAccountsRoute = AdAccountsRouteImport.update({
  id: '/ad-accounts',
  path: '/ad-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsTaskIdRoute = OperationsTaskIdRouteImport.update({
  id: '/operations_/$taskId',
  path: '/operations/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const FbAccountsIdRoute = FbAccountsIdRouteImport.update({
  id: '/fb-accounts_/$id',
  path: '/fb-accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin_/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIamRoute = AdminIamRouteImport.update({
  id: '/admin_/iam',
  path: '/admin/iam',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompanyRoute = AdminCompanyRouteImport.update({
  id: '/admin_/company',
  path: '/admin/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin_/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdAccountsIdRoute = AdAccountsIdRouteImport.update({
  id: '/ad-accounts_/$id',
  path: '/ad-accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthFbCallbackRoute = OauthFbCallbackRouteImport.update({
  id: '/oauth/fb/callback',
  path: '/oauth/fb/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsTaskIdRoute = AdminOperationsTaskIdRouteImport.update({
  id: '/admin_/operations_/$taskId',
  path: '/admin/operations/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdAccountsIdCampaignsCidRoute =
  AdAccountsIdCampaignsCidRouteImport.update({
    id: '/ad-accounts_/$id_/campaigns_/$cid',
    path: '/ad-accounts/$id/campaigns/$cid',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdAccountsIdCampaignsCidAdsetsAsidRoute =
  AdAccountsIdCampaignsCidAdsetsAsidRouteImport.update({
    id: '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid',
    path: '/ad-accounts/$id/campaigns/$cid/adsets/$asid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ad-accounts': typeof AdAccountsRoute
  '/admin': typeof AdminRoute
  '/archives': typeof ArchivesRoute
  '/fb-accounts': typeof FbAccountsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/ad-accounts/$id': typeof AdAccountsIdRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/iam': typeof AdminIamRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/fb-accounts/$id': typeof FbAccountsIdRoute
  '/operations/$taskId': typeof OperationsTaskIdRoute
  '/admin/operations/$taskId': typeof AdminOperationsTaskIdRoute
  '/oauth/fb/callback': typeof OauthFbCallbackRoute
  '/ad-accounts/$id/campaigns/$cid': typeof AdAccountsIdCampaignsCidRoute
  '/ad-accounts/$id/campaigns/$cid/adsets/$asid': typeof AdAccountsIdCampaignsCidAdsetsAsidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ad-accounts': typeof AdAccountsRoute
  '/admin': typeof AdminRoute
  '/archives': typeof ArchivesRoute
  '/fb-accounts': typeof FbAccountsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/ad-accounts/$id': typeof AdAccountsIdRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/iam': typeof AdminIamRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/fb-accounts/$id': typeof FbAccountsIdRoute
  '/operations/$taskId': typeof OperationsTaskIdRoute
  '/admin/operations/$taskId': typeof AdminOperationsTaskIdRoute
  '/oauth/fb/callback': typeof OauthFbCallbackRoute
  '/ad-accounts/$id/campaigns/$cid': typeof AdAccountsIdCampaignsCidRoute
  '/ad-accounts/$id/campaigns/$cid/adsets/$asid': typeof AdAccountsIdCampaignsCidAdsetsAsidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ad-accounts': typeof AdAccountsRoute
  '/admin': typeof AdminRoute
  '/archives': typeof ArchivesRoute
  '/fb-accounts': typeof FbAccountsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/ad-accounts_/$id': typeof AdAccountsIdRoute
  '/admin_/audit': typeof AdminAuditRoute
  '/admin_/company': typeof AdminCompanyRoute
  '/admin_/iam': typeof AdminIamRoute
  '/admin_/operations': typeof AdminOperationsRoute
  '/admin_/users': typeof AdminUsersRoute
  '/fb-accounts_/$id': typeof FbAccountsIdRoute
  '/operations_/$taskId': typeof OperationsTaskIdRoute
  '/admin_/operations_/$taskId': typeof AdminOperationsTaskIdRoute
  '/oauth/fb/callback': typeof OauthFbCallbackRoute
  '/ad-accounts_/$id_/campaigns_/$cid': typeof AdAccountsIdCampaignsCidRoute
  '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid': typeof AdAccountsIdCampaignsCidAdsetsAsidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ad-accounts'
    | '/admin'
    | '/archives'
    | '/fb-accounts'
    | '/login'
    | '/operations'
    | '/ad-accounts/$id'
    | '/admin/audit'
    | '/admin/company'
    | '/admin/iam'
    | '/admin/operations'
    | '/admin/users'
    | '/fb-accounts/$id'
    | '/operations/$taskId'
    | '/admin/operations/$taskId'
    | '/oauth/fb/callback'
    | '/ad-accounts/$id/campaigns/$cid'
    | '/ad-accounts/$id/campaigns/$cid/adsets/$asid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ad-accounts'
    | '/admin'
    | '/archives'
    | '/fb-accounts'
    | '/login'
    | '/operations'
    | '/ad-accounts/$id'
    | '/admin/audit'
    | '/admin/company'
    | '/admin/iam'
    | '/admin/operations'
    | '/admin/users'
    | '/fb-accounts/$id'
    | '/operations/$taskId'
    | '/admin/operations/$taskId'
    | '/oauth/fb/callback'
    | '/ad-accounts/$id/campaigns/$cid'
    | '/ad-accounts/$id/campaigns/$cid/adsets/$asid'
  id:
    | '__root__'
    | '/'
    | '/ad-accounts'
    | '/admin'
    | '/archives'
    | '/fb-accounts'
    | '/login'
    | '/operations'
    | '/ad-accounts_/$id'
    | '/admin_/audit'
    | '/admin_/company'
    | '/admin_/iam'
    | '/admin_/operations'
    | '/admin_/users'
    | '/fb-accounts_/$id'
    | '/operations_/$taskId'
    | '/admin_/operations_/$taskId'
    | '/oauth/fb/callback'
    | '/ad-accounts_/$id_/campaigns_/$cid'
    | '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdAccountsRoute: typeof AdAccountsRoute
  AdminRoute: typeof AdminRoute
  ArchivesRoute: typeof ArchivesRoute
  FbAccountsRoute: typeof FbAccountsRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  AdAccountsIdRoute: typeof AdAccountsIdRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCompanyRoute: typeof AdminCompanyRoute
  AdminIamRoute: typeof AdminIamRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  FbAccountsIdRoute: typeof FbAccountsIdRoute
  OperationsTaskIdRoute: typeof OperationsTaskIdRoute
  AdminOperationsTaskIdRoute: typeof AdminOperationsTaskIdRoute
  OauthFbCallbackRoute: typeof OauthFbCallbackRoute
  AdAccountsIdCampaignsCidRoute: typeof AdAccountsIdCampaignsCidRoute
  AdAccountsIdCampaignsCidAdsetsAsidRoute: typeof AdAccountsIdCampaignsCidAdsetsAsidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fb-accounts': {
      id: '/fb-accounts'
      path: '/fb-accounts'
      fullPath: '/fb-accounts'
      preLoaderRoute: typeof FbAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-accounts': {
      id: '/ad-accounts'
      path: '/ad-accounts'
      fullPath: '/ad-accounts'
      preLoaderRoute: typeof AdAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations_/$taskId': {
      id: '/operations_/$taskId'
      path: '/operations/$taskId'
      fullPath: '/operations/$taskId'
      preLoaderRoute: typeof OperationsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fb-accounts_/$id': {
      id: '/fb-accounts_/$id'
      path: '/fb-accounts/$id'
      fullPath: '/fb-accounts/$id'
      preLoaderRoute: typeof FbAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/operations': {
      id: '/admin_/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/iam': {
      id: '/admin_/iam'
      path: '/admin/iam'
      fullPath: '/admin/iam'
      preLoaderRoute: typeof AdminIamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/company': {
      id: '/admin_/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AdminCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/audit': {
      id: '/admin_/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-accounts_/$id': {
      id: '/ad-accounts_/$id'
      path: '/ad-accounts/$id'
      fullPath: '/ad-accounts/$id'
      preLoaderRoute: typeof AdAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/fb/callback': {
      id: '/oauth/fb/callback'
      path: '/oauth/fb/callback'
      fullPath: '/oauth/fb/callback'
      preLoaderRoute: typeof OauthFbCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/operations_/$taskId': {
      id: '/admin_/operations_/$taskId'
      path: '/admin/operations/$taskId'
      fullPath: '/admin/operations/$taskId'
      preLoaderRoute: typeof AdminOperationsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-accounts_/$id_/campaigns_/$cid': {
      id: '/ad-accounts_/$id_/campaigns_/$cid'
      path: '/ad-accounts/$id/campaigns/$cid'
      fullPath: '/ad-accounts/$id/campaigns/$cid'
      preLoaderRoute: typeof AdAccountsIdCampaignsCidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid': {
      id: '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid'
      path: '/ad-accounts/$id/campaigns/$cid/adsets/$asid'
      fullPath: '/ad-accounts/$id/campaigns/$cid/adsets/$asid'
      preLoaderRoute: typeof AdAccountsIdCampaignsCidAdsetsAsidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdAccountsRoute: AdAccountsRoute,
  AdminRoute: AdminRoute,
  ArchivesRoute: ArchivesRoute,
  FbAccountsRoute: FbAccountsRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  AdAccountsIdRoute: AdAccountsIdRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCompanyRoute: AdminCompanyRoute,
  AdminIamRoute: AdminIamRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  FbAccountsIdRoute: FbAccountsIdRoute,
  OperationsTaskIdRoute: OperationsTaskIdRoute,
  AdminOperationsTaskIdRoute: AdminOperationsTaskIdRoute,
  OauthFbCallbackRoute: OauthFbCallbackRoute,
  AdAccountsIdCampaignsCidRoute: AdAccountsIdCampaignsCidRoute,
  AdAccountsIdCampaignsCidAdsetsAsidRoute:
    AdAccountsIdCampaignsCidAdsetsAsidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
