/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FbAccountsRouteImport } from './routes/fb-accounts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FbAccountsIdRouteImport } from './routes/fb-accounts_.$id'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdAccountsIdRouteImport } from './routes/ad-accounts_.$id'
import { Route as OauthFbCallbackRouteImport } from './routes/oauth.fb.callback'
import { Route as AdAccountsIdCampaignsCidRouteImport } from './routes/ad-accounts_.$id_.campaigns_.$cid'
import { Route as AdAccountsIdCampaignsCidAdsetsAsidRouteImport } from './routes/ad-accounts_.$id_.campaigns_.$cid_.adsets_.$asid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FbAccountsRoute = FbAccountsRouteImport.update({
  id: '/fb-accounts',
  path: '/fb-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FbAccountsIdRoute = FbAccountsIdRouteImport.update({
  id: '/fb-accounts_/$id',
  path: '/fb-accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdAccountsIdRoute = AdAccountsIdRouteImport.update({
  id: '/ad-accounts_/$id',
  path: '/ad-accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthFbCallbackRoute = OauthFbCallbackRouteImport.update({
  id: '/oauth/fb/callback',
  path: '/oauth/fb/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdAccountsIdCampaignsCidRoute =
  AdAccountsIdCampaignsCidRouteImport.update({
    id: '/ad-accounts_/$id_/campaigns_/$cid',
    path: '/ad-accounts/$id/campaigns/$cid',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdAccountsIdCampaignsCidAdsetsAsidRoute =
  AdAccountsIdCampaignsCidAdsetsAsidRouteImport.update({
    id: '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid',
    path: '/ad-accounts/$id/campaigns/$cid/adsets/$asid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fb-accounts': typeof FbAccountsRoute
  '/login': typeof LoginRoute
  '/ad-accounts/$id': typeof AdAccountsIdRoute
  '/admin/users': typeof AdminUsersRoute
  '/fb-accounts/$id': typeof FbAccountsIdRoute
  '/oauth/fb/callback': typeof OauthFbCallbackRoute
  '/ad-accounts/$id/campaigns/$cid': typeof AdAccountsIdCampaignsCidRoute
  '/ad-accounts/$id/campaigns/$cid/adsets/$asid': typeof AdAccountsIdCampaignsCidAdsetsAsidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fb-accounts': typeof FbAccountsRoute
  '/login': typeof LoginRoute
  '/ad-accounts/$id': typeof AdAccountsIdRoute
  '/admin/users': typeof AdminUsersRoute
  '/fb-accounts/$id': typeof FbAccountsIdRoute
  '/oauth/fb/callback': typeof OauthFbCallbackRoute
  '/ad-accounts/$id/campaigns/$cid': typeof AdAccountsIdCampaignsCidRoute
  '/ad-accounts/$id/campaigns/$cid/adsets/$asid': typeof AdAccountsIdCampaignsCidAdsetsAsidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/fb-accounts': typeof FbAccountsRoute
  '/login': typeof LoginRoute
  '/ad-accounts_/$id': typeof AdAccountsIdRoute
  '/admin_/users': typeof AdminUsersRoute
  '/fb-accounts_/$id': typeof FbAccountsIdRoute
  '/oauth/fb/callback': typeof OauthFbCallbackRoute
  '/ad-accounts_/$id_/campaigns_/$cid': typeof AdAccountsIdCampaignsCidRoute
  '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid': typeof AdAccountsIdCampaignsCidAdsetsAsidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/fb-accounts'
    | '/login'
    | '/ad-accounts/$id'
    | '/admin/users'
    | '/fb-accounts/$id'
    | '/oauth/fb/callback'
    | '/ad-accounts/$id/campaigns/$cid'
    | '/ad-accounts/$id/campaigns/$cid/adsets/$asid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/fb-accounts'
    | '/login'
    | '/ad-accounts/$id'
    | '/admin/users'
    | '/fb-accounts/$id'
    | '/oauth/fb/callback'
    | '/ad-accounts/$id/campaigns/$cid'
    | '/ad-accounts/$id/campaigns/$cid/adsets/$asid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/fb-accounts'
    | '/login'
    | '/ad-accounts_/$id'
    | '/admin_/users'
    | '/fb-accounts_/$id'
    | '/oauth/fb/callback'
    | '/ad-accounts_/$id_/campaigns_/$cid'
    | '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FbAccountsRoute: typeof FbAccountsRoute
  LoginRoute: typeof LoginRoute
  AdAccountsIdRoute: typeof AdAccountsIdRoute
  AdminUsersRoute: typeof AdminUsersRoute
  FbAccountsIdRoute: typeof FbAccountsIdRoute
  OauthFbCallbackRoute: typeof OauthFbCallbackRoute
  AdAccountsIdCampaignsCidRoute: typeof AdAccountsIdCampaignsCidRoute
  AdAccountsIdCampaignsCidAdsetsAsidRoute: typeof AdAccountsIdCampaignsCidAdsetsAsidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fb-accounts': {
      id: '/fb-accounts'
      path: '/fb-accounts'
      fullPath: '/fb-accounts'
      preLoaderRoute: typeof FbAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fb-accounts_/$id': {
      id: '/fb-accounts_/$id'
      path: '/fb-accounts/$id'
      fullPath: '/fb-accounts/$id'
      preLoaderRoute: typeof FbAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-accounts_/$id': {
      id: '/ad-accounts_/$id'
      path: '/ad-accounts/$id'
      fullPath: '/ad-accounts/$id'
      preLoaderRoute: typeof AdAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/fb/callback': {
      id: '/oauth/fb/callback'
      path: '/oauth/fb/callback'
      fullPath: '/oauth/fb/callback'
      preLoaderRoute: typeof OauthFbCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-accounts_/$id_/campaigns_/$cid': {
      id: '/ad-accounts_/$id_/campaigns_/$cid'
      path: '/ad-accounts/$id/campaigns/$cid'
      fullPath: '/ad-accounts/$id/campaigns/$cid'
      preLoaderRoute: typeof AdAccountsIdCampaignsCidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid': {
      id: '/ad-accounts_/$id_/campaigns_/$cid_/adsets_/$asid'
      path: '/ad-accounts/$id/campaigns/$cid/adsets/$asid'
      fullPath: '/ad-accounts/$id/campaigns/$cid/adsets/$asid'
      preLoaderRoute: typeof AdAccountsIdCampaignsCidAdsetsAsidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FbAccountsRoute: FbAccountsRoute,
  LoginRoute: LoginRoute,
  AdAccountsIdRoute: AdAccountsIdRoute,
  AdminUsersRoute: AdminUsersRoute,
  FbAccountsIdRoute: FbAccountsIdRoute,
  OauthFbCallbackRoute: OauthFbCallbackRoute,
  AdAccountsIdCampaignsCidRoute: AdAccountsIdCampaignsCidRoute,
  AdAccountsIdCampaignsCidAdsetsAsidRoute:
    AdAccountsIdCampaignsCidAdsetsAsidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
